name: AimTP
main: dktapps\AimTP\Main
version: 0.0.1
api: 4.0.0
load: POSTWORLD
author: dktapps
description: Teleport where your crosshair is aiming
website: https://github.com/pmmp/PocketMine-DevTools
commands:
 tpstick:
  description: "Gives the player a teleporter stick"
  usage: "/tpstick"
  permission: aimtp.give

permissions:
 aimtp.give:
  default: op
  description: "Allows the player to use /tpstick"
