name: AimTP
main: dktapps\AimTP\Main
version: 0.1.0
api: [3.0.0, 4.0.0, 3.2.0, 3.2.3, 3.5.5]
load: POSTWORLD
author: dktapps
description: Teleport where your crosshair is aiming
website: https://github.com/dktapps-pm-pl/AimTP
commands:
 tpstick:
  description: "Gives the player a teleporter stick"
  usage: "/tpstick"
  permission: aimtp.give

permissions:
 aimtp.give:
  default: op
  description: "Allows the player to use /tpstick"
 aimtp.use:
  default: op
  description: "Allows the player to use a teleporter stick item"
